---
- name: "Copying SSH Config"
  copy:
    src: "{{ role_path }}/files/sshd_config"
    dest: "/etc/ssh/sshd_config"
  become: true
  become_method: sudo

- name: "Enable SSH Service"
  ansible.builtin.service:
    name: ssh
    enabled: yes
  become: true
  become_method: sudo
